# Generated by Django 4.2.9 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'наличные'), ('spend', 'перевод на счет')], max_length=32, verbose_name='Способ оплаты'),
        ),
    ]
