# Generated by Django 4.2.9 on 2024-05-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_sessions_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="sessions_id",
            new_name="session_id",
        ),
    ]
