# Generated by Django 4.2.9 on 2024-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
