# Generated by Django 4.2.9 on 2024-05-20 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0005_course_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseSubscription",
            new_name="Subscription",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="user",
            new_name="subscriber",
        ),
    ]
