# Generated by Django 4.2.9 on 2024-05-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_rename_coursesubscription_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
