# Generated by Django 4.2.9 on 2024-05-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_subscription_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
    ]
